# UI
MAIN_PAGE_URL = "https://www.chitai-gorod.ru/"

# API
API_V1_URL = "https://web-gate.chitai-gorod.ru/api/v1/"
USER_AUTH_TOKEN = "Bearer yJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL3VzZXItcmlnaHQiLCJzdWIiOjIyMzY0NTY4LCJpYXQiOjE3NjEzMDM1NzQsImV4cCI6MTc2MTMwNzE3NCwidHlwZSI6MjAsImp0aSI6IjAxOWExNWRmLWI5NGMtNzRhNC1hNTUwLWM5NTg2ZDA0ZmU0ZCIsInJvbGVzIjoxMH0.LeZQbrwL8QxGUobQjXzPa7RZJ_zD9lZaAjpU1eM-HYM"
